// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: proto/sessions/v1/sessions.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSessionRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AccessToken           string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	AccessTokenExpiresAt  string                 `protobuf:"bytes,2,opt,name=access_token_expires_at,json=accessTokenExpiresAt,proto3" json:"access_token_expires_at,omitempty"`
	RefreshToken          string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	RefreshTokenExpiresAt string                 `protobuf:"bytes,4,opt,name=refresh_token_expires_at,json=refreshTokenExpiresAt,proto3" json:"refresh_token_expires_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_proto_sessions_v1_sessions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sessions_v1_sessions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_sessions_v1_sessions_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *CreateSessionRequest) GetAccessTokenExpiresAt() string {
	if x != nil {
		return x.AccessTokenExpiresAt
	}
	return ""
}

func (x *CreateSessionRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *CreateSessionRequest) GetRefreshTokenExpiresAt() string {
	if x != nil {
		return x.RefreshTokenExpiresAt
	}
	return ""
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_proto_sessions_v1_sessions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sessions_v1_sessions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_sessions_v1_sessions_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateSessionResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *CreateSessionResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *CreateSessionResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetSessionRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AccessToken           string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	AccessTokenExpiresAt  string                 `protobuf:"bytes,2,opt,name=access_token_expires_at,json=accessTokenExpiresAt,proto3" json:"access_token_expires_at,omitempty"`
	RefreshToken          string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	RefreshTokenExpiresAt string                 `protobuf:"bytes,4,opt,name=refresh_token_expires_at,json=refreshTokenExpiresAt,proto3" json:"refresh_token_expires_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_proto_sessions_v1_sessions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sessions_v1_sessions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_sessions_v1_sessions_proto_rawDescGZIP(), []int{2}
}

func (x *GetSessionRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *GetSessionRequest) GetAccessTokenExpiresAt() string {
	if x != nil {
		return x.AccessTokenExpiresAt
	}
	return ""
}

func (x *GetSessionRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *GetSessionRequest) GetRefreshTokenExpiresAt() string {
	if x != nil {
		return x.RefreshTokenExpiresAt
	}
	return ""
}

type GetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	RevokedAt     string                 `protobuf:"bytes,4,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_proto_sessions_v1_sessions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sessions_v1_sessions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_sessions_v1_sessions_proto_rawDescGZIP(), []int{3}
}

func (x *GetSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetSessionResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *GetSessionResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *GetSessionResponse) GetRevokedAt() string {
	if x != nil {
		return x.RevokedAt
	}
	return ""
}

func (x *GetSessionResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RefreshSessionRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AccessToken           string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	AccessTokenExpiresAt  string                 `protobuf:"bytes,2,opt,name=access_token_expires_at,json=accessTokenExpiresAt,proto3" json:"access_token_expires_at,omitempty"`
	RefreshToken          string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	RefreshTokenExpiresAt string                 `protobuf:"bytes,4,opt,name=refresh_token_expires_at,json=refreshTokenExpiresAt,proto3" json:"refresh_token_expires_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RefreshSessionRequest) Reset() {
	*x = RefreshSessionRequest{}
	mi := &file_proto_sessions_v1_sessions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshSessionRequest) ProtoMessage() {}

func (x *RefreshSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sessions_v1_sessions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshSessionRequest.ProtoReflect.Descriptor instead.
func (*RefreshSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_sessions_v1_sessions_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshSessionRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshSessionRequest) GetAccessTokenExpiresAt() string {
	if x != nil {
		return x.AccessTokenExpiresAt
	}
	return ""
}

func (x *RefreshSessionRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshSessionRequest) GetRefreshTokenExpiresAt() string {
	if x != nil {
		return x.RefreshTokenExpiresAt
	}
	return ""
}

type RefreshSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	RevokedAt     string                 `protobuf:"bytes,4,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshSessionResponse) Reset() {
	*x = RefreshSessionResponse{}
	mi := &file_proto_sessions_v1_sessions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshSessionResponse) ProtoMessage() {}

func (x *RefreshSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sessions_v1_sessions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshSessionResponse.ProtoReflect.Descriptor instead.
func (*RefreshSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_sessions_v1_sessions_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RefreshSessionResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshSessionResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *RefreshSessionResponse) GetRevokedAt() string {
	if x != nil {
		return x.RevokedAt
	}
	return ""
}

func (x *RefreshSessionResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_proto_sessions_v1_sessions_proto protoreflect.FileDescriptor

const file_proto_sessions_v1_sessions_proto_rawDesc = "" +
	"\n" +
	" proto/sessions/v1/sessions.proto\x12\vsessions.v1\"\xce\x01\n" +
	"\x14CreateSessionRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x125\n" +
	"\x17access_token_expires_at\x18\x02 \x01(\tR\x14accessTokenExpiresAt\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x127\n" +
	"\x18refresh_token_expires_at\x18\x04 \x01(\tR\x15refreshTokenExpiresAt\"\x93\x01\n" +
	"\x15CreateSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\tR\texpiresAt\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"\xcb\x01\n" +
	"\x11GetSessionRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x125\n" +
	"\x17access_token_expires_at\x18\x02 \x01(\tR\x14accessTokenExpiresAt\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x127\n" +
	"\x18refresh_token_expires_at\x18\x04 \x01(\tR\x15refreshTokenExpiresAt\"\xaf\x01\n" +
	"\x12GetSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\tR\texpiresAt\x12\x1d\n" +
	"\n" +
	"revoked_at\x18\x04 \x01(\tR\trevokedAt\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\"\xcf\x01\n" +
	"\x15RefreshSessionRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x125\n" +
	"\x17access_token_expires_at\x18\x02 \x01(\tR\x14accessTokenExpiresAt\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x127\n" +
	"\x18refresh_token_expires_at\x18\x04 \x01(\tR\x15refreshTokenExpiresAt\"\xb3\x01\n" +
	"\x16RefreshSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\tR\texpiresAt\x12\x1d\n" +
	"\n" +
	"revoked_at\x18\x04 \x01(\tR\trevokedAt\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId2\x98\x02\n" +
	"\x0eSessionService\x12X\n" +
	"\rCreateSession\x12!.sessions.v1.CreateSessionRequest\x1a\".sessions.v1.CreateSessionResponse\"\x00\x12O\n" +
	"\n" +
	"GetSession\x12\x1e.sessions.v1.GetSessionRequest\x1a\x1f.sessions.v1.GetSessionResponse\"\x00\x12[\n" +
	"\x0eRefreshSession\x12\".sessions.v1.RefreshSessionRequest\x1a#.sessions.v1.RefreshSessionResponse\"\x00B4Z2github.com/tobib-dev/frnkstn/api/proto/sessions/v1b\x06proto3"

var (
	file_proto_sessions_v1_sessions_proto_rawDescOnce sync.Once
	file_proto_sessions_v1_sessions_proto_rawDescData []byte
)

func file_proto_sessions_v1_sessions_proto_rawDescGZIP() []byte {
	file_proto_sessions_v1_sessions_proto_rawDescOnce.Do(func() {
		file_proto_sessions_v1_sessions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sessions_v1_sessions_proto_rawDesc), len(file_proto_sessions_v1_sessions_proto_rawDesc)))
	})
	return file_proto_sessions_v1_sessions_proto_rawDescData
}

var file_proto_sessions_v1_sessions_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_sessions_v1_sessions_proto_goTypes = []any{
	(*CreateSessionRequest)(nil),   // 0: sessions.v1.CreateSessionRequest
	(*CreateSessionResponse)(nil),  // 1: sessions.v1.CreateSessionResponse
	(*GetSessionRequest)(nil),      // 2: sessions.v1.GetSessionRequest
	(*GetSessionResponse)(nil),     // 3: sessions.v1.GetSessionResponse
	(*RefreshSessionRequest)(nil),  // 4: sessions.v1.RefreshSessionRequest
	(*RefreshSessionResponse)(nil), // 5: sessions.v1.RefreshSessionResponse
}
var file_proto_sessions_v1_sessions_proto_depIdxs = []int32{
	0, // 0: sessions.v1.SessionService.CreateSession:input_type -> sessions.v1.CreateSessionRequest
	2, // 1: sessions.v1.SessionService.GetSession:input_type -> sessions.v1.GetSessionRequest
	4, // 2: sessions.v1.SessionService.RefreshSession:input_type -> sessions.v1.RefreshSessionRequest
	1, // 3: sessions.v1.SessionService.CreateSession:output_type -> sessions.v1.CreateSessionResponse
	3, // 4: sessions.v1.SessionService.GetSession:output_type -> sessions.v1.GetSessionResponse
	5, // 5: sessions.v1.SessionService.RefreshSession:output_type -> sessions.v1.RefreshSessionResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sessions_v1_sessions_proto_init() }
func file_proto_sessions_v1_sessions_proto_init() {
	if File_proto_sessions_v1_sessions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sessions_v1_sessions_proto_rawDesc), len(file_proto_sessions_v1_sessions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sessions_v1_sessions_proto_goTypes,
		DependencyIndexes: file_proto_sessions_v1_sessions_proto_depIdxs,
		MessageInfos:      file_proto_sessions_v1_sessions_proto_msgTypes,
	}.Build()
	File_proto_sessions_v1_sessions_proto = out.File
	file_proto_sessions_v1_sessions_proto_goTypes = nil
	file_proto_sessions_v1_sessions_proto_depIdxs = nil
}
