package main

import (
	"context"
	"log/slog"
	"testing"
	"time"

	"github.com/gocql/gocql"
	dmsV1 "github.com/tobib-dev/frnkstn-proto/dms/v1"
	"github.com/tobib-dev/frnkstn/api/db"
)

type testDMStore struct {
	sent           db.DM
	message        db.DM
	messages       []db.DM
	userMetadata   []db.DMMetadata
	requestedDMID  gocql.UUID
	requestedUser  gocql.UUID
	requestedMsgID gocql.UUID
}

func (s *testDMStore) SendMessage(_ context.Context, message db.DM) error {
	s.sent = message
	return nil
}

func (s *testDMStore) GetMessage(_ context.Context, dmID, messageID gocql.UUID) (db.DM, error) {
	s.requestedDMID, s.requestedMsgID = dmID, messageID
	return s.message, nil
}

func (s *testDMStore) GetMessages(_ context.Context, dmID gocql.UUID) ([]db.DM, error) {
	s.requestedDMID = dmID
	return s.messages, nil
}

func (s *testDMStore) GetMessagesByUser(_ context.Context, userID gocql.UUID) ([]db.DMMetadata, error) {
	s.requestedUser = userID
	return s.userMetadata, nil
}

func (s *testDMStore) SubscribeMessages(context.Context, db.MessageStreamParams) ([]db.DM, error) {
	return nil, nil
}

func TestSendMessagesGeneratesMessageID(t *testing.T) {
	dmID, authorID, receiverID := gocql.TimeUUID(), gocql.TimeUUID(), gocql.TimeUUID()
	store := &testDMStore{}
	users := &testUserStore{users: map[gocql.UUID]db.User{
		authorID:   {ID: authorID},
		receiverID: {ID: receiverID},
	}}
	service := &directMessageService{cfg: &Config{logger: slog.Default()}, store: store, users: users}

	response, err := service.SendMessages(context.Background(), &dmsV1.SendMessagesRequest{Item: &dmsV1.DirectMessageItem{
		DmId: dmID.String(), AuthorId: authorID.String(), ReceiverId: receiverID.String(), Content: " hello ", MessageId: "ignored",
	}})
	if err != nil {
		t.Fatal(err)
	}
	if store.sent.MessageID == (gocql.UUID{}) || store.sent.MessageID.Version() != 1 || response.Item.MessageId != store.sent.MessageID.String() {
		t.Fatalf("message ID was not generated by the service: stored=%s response=%q", store.sent.MessageID, response.Item.MessageId)
	}
	if store.sent.ID != dmID || store.sent.AuthorID != authorID || store.sent.ReceiverID != receiverID || store.sent.Content != "hello" {
		t.Fatalf("unexpected stored message: %+v", store.sent)
	}
}

func TestGetMessagesAndMetadataReturnEveryItem(t *testing.T) {
	dmID, secondDMID, userID := gocql.TimeUUID(), gocql.TimeUUID(), gocql.TimeUUID()
	messages := []db.DM{
		{ID: dmID, MessageID: gocql.TimeUUID(), Content: "one"},
		{ID: dmID, MessageID: gocql.TimeUUID(), Content: "two"},
	}
	metadata := []db.DMMetadata{
		{ID: dmID, UserID: userID, LastMessageTime: time.Unix(2, 0)},
		{ID: secondDMID, UserID: userID, LastMessageTime: time.Unix(1, 0)},
	}
	store := &testDMStore{messages: messages, userMetadata: metadata}
	users := &testUserStore{users: map[gocql.UUID]db.User{userID: {ID: userID}}}
	service := &directMessageService{cfg: &Config{logger: slog.Default()}, store: store, users: users}

	byDM, err := service.GetMessages(context.Background(), &dmsV1.GetMessagesRequest{Item: &dmsV1.DirectMessageItem{DmId: dmID.String()}})
	if err != nil {
		t.Fatal(err)
	}
	byUser, err := service.GetMessagesByUser(context.Background(), &dmsV1.GetMessagesByUserRequest{UserId: userID.String()})
	if err != nil {
		t.Fatal(err)
	}
	if len(byDM.Items) != len(messages) || len(byUser.Items) != len(metadata) {
		t.Fatalf("results were truncated: messages=%d metadata=%d", len(byDM.Items), len(byUser.Items))
	}
	if byUser.Items[0].DmId != dmID.String() || !byUser.Items[0].LastMessageTime.AsTime().Equal(metadata[0].LastMessageTime) {
		t.Fatalf("unexpected metadata: %+v", byUser.Items[0])
	}
	if store.requestedDMID != dmID || store.requestedUser != userID {
		t.Fatalf("unexpected query IDs: DM=%s user=%s", store.requestedDMID, store.requestedUser)
	}
}
