package main

import (
	"context"
	"log/slog"
	"testing"

	"github.com/gocql/gocql"
	friendsv1 "github.com/tobib-dev/frnkstn-proto/friends/v1"
	"github.com/tobib-dev/frnkstn/api/db"
)

type testFriendStore struct {
	friend          db.Friend
	rejected        db.Friend
	added           int
	removedID       gocql.UUID
	removedForUser  gocql.UUID
	getFriendsCalls int
}

func (s *testFriendStore) AddFriend(_ context.Context, friend db.Friend) (db.Friend, error) {
	s.added++
	friend.Status = "pending"
	s.friend = friend
	return friend, nil
}

func (s *testFriendStore) AcceptFriend(_ context.Context, friend db.Friend) (db.Friend, error) {
	friend.Status = "accepted"
	return friend, nil
}

func (s *testFriendStore) RejectFriend(_ context.Context, friend db.Friend) (db.Friend, error) {
	friend.Status = "rejected"
	s.rejected = friend
	return friend, nil
}

func (s *testFriendStore) RemoveFriend(_ context.Context, friendshipID, userID gocql.UUID) error {
	s.removedID = friendshipID
	s.removedForUser = userID
	return nil
}
func (s *testFriendStore) GetFriend(_ context.Context, id gocql.UUID) (db.Friend, error) {
	if s.friend.ID != id {
		return db.Friend{}, gocql.ErrNotFound
	}
	return s.friend, nil
}
func (s *testFriendStore) GetFriends(_ context.Context, userID gocql.UUID) ([]db.Friend, error) {
	s.getFriendsCalls++
	if s.friend.UserID != userID {
		return nil, nil
	}
	return []db.Friend{s.friend}, nil
}

func TestRemoveFriendUsesFriendshipID(t *testing.T) {
	friendship := db.Friend{ID: gocql.TimeUUID(), UserID: gocql.TimeUUID(), FriendID: gocql.TimeUUID()}
	store := &testFriendStore{friend: friendship}
	service := &FriendService{cfg: &Config{logger: slog.Default()}, store: store}

	response, err := service.RemoveFriend(context.Background(), &friendsv1.RemoveFriendRequest{
		FriendshipId: friendship.ID.String(),
		UserId:       friendship.UserID.String(),
		FriendId:     friendship.FriendID.String(),
	})
	if err != nil {
		t.Fatal(err)
	}
	if response.Status != "removed" {
		t.Fatalf("unexpected status: %q", response.Status)
	}
	if store.removedID != friendship.ID || store.removedForUser != friendship.UserID {
		t.Fatalf("unexpected remove arguments: friendship=%s user=%s", store.removedID, store.removedForUser)
	}
	if store.getFriendsCalls != 0 {
		t.Fatalf("RemoveFriend listed friends %d times", store.getFriendsCalls)
	}
}

func TestRejectFriendUsesFriendshipID(t *testing.T) {
	friendship := db.Friend{ID: gocql.TimeUUID(), UserID: gocql.TimeUUID(), FriendID: gocql.TimeUUID()}
	store := &testFriendStore{friend: friendship}
	service := &FriendService{cfg: &Config{logger: slog.Default()}, store: store}

	response, err := service.RejectFriend(context.Background(), &friendsv1.RejectFriendRequest{
		FriendshipId: friendship.ID.String(),
		UserId:       friendship.UserID.String(),
		FriendId:     friendship.FriendID.String(),
	})
	if err != nil {
		t.Fatal(err)
	}
	if response.FriendshipId != friendship.ID.String() || response.Status != "rejected" {
		t.Fatalf("unexpected response: %+v", response)
	}
	if store.rejected.ID != friendship.ID {
		t.Fatalf("unexpected rejected friendship: %+v", store.rejected)
	}
	if store.getFriendsCalls != 0 {
		t.Fatalf("RejectFriend listed friends %d times", store.getFriendsCalls)
	}
}

func TestAddFriendGeneratesTimeUUIDOnServer(t *testing.T) {
	userID, friendID := gocql.TimeUUID(), gocql.TimeUUID()
	users := &testUserStore{users: map[gocql.UUID]db.User{
		userID:   {ID: userID, Username: "alice"},
		friendID: {ID: friendID, Username: "bob"},
	}}
	store := &testFriendStore{}
	service := &FriendService{cfg: &Config{logger: slog.Default()}, store: store, users: users}

	response, err := service.AddFriend(context.Background(), &friendsv1.AddFriendRequest{UserId: userID.String(), FriendId: friendID.String()})
	if err != nil {
		t.Fatal(err)
	}
	if store.added != 1 || store.friend.ID == (gocql.UUID{}) || store.friend.ID.Version() != 1 {
		t.Fatalf("friendship ID was not generated by the service: %+v", store.friend)
	}
	if response.FriendshipId != store.friend.ID.String() || response.Status != "pending" || store.friend.FriendName != "bob" {
		t.Fatalf("unexpected response or stored friend: response=%+v friend=%+v", response, store.friend)
	}
}
